name: Build cover letter
on:
  push:
    paths:
      - 'manuscript/cover_letter/**'
      - '.github/workflows/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ./manuscript/cover_letter/
          root_file: cover_letter.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ./manuscript/cover_letter/cover_letter.pdf
